version: "3.8"

services:
  tts-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openai-tts-tg-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
